version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: hazar-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: YourStrongPassword
      MYSQL_DATABASE: HazarDb
      MYSQL_USER: hazar
      MYSQL_PASSWORD: HazarPassword123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

